import type { MetadataRoute } from "next";
import { SITE, ALL_GAMES, PROMOTIONS } from "@/lib/catalog";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: `${SITE.url}/`, lastModified: now, changeFrequency: "daily", priority: 1 },
    { url: `${SITE.url}/games`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${SITE.url}/popular`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/sports`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/sports/live`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${SITE.url}/sports/results`, lastModified: now, changeFrequency: "daily", priority: 0.5 },
    { url: `${SITE.url}/sports/cricket`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${SITE.url}/cricket`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/cockfighting`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${SITE.url}/slots`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/casino`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/exchange`, lastModified: now, changeFrequency: "daily", priority: 0.7 },
    { url: `${SITE.url}/table`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${SITE.url}/fishing`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${SITE.url}/lottery`, lastModified: now, changeFrequency: "weekly", priority: 0.6 },
    { url: `${SITE.url}/arcade`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${SITE.url}/crash`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/promotions`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${SITE.url}/vip`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE.url}/leaderboard`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${SITE.url}/brands`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${SITE.url}/guide`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/referral`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/forum`, lastModified: now, changeFrequency: "weekly", priority: 0.4 },
    { url: `${SITE.url}/payments`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/tournaments`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${SITE.url}/cashback`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${SITE.url}/rewards`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${SITE.url}/status`, lastModified: now, changeFrequency: "daily", priority: 0.3 },
    { url: `${SITE.url}/provider-status`, lastModified: now, changeFrequency: "daily", priority: 0.3 },
    { url: `${SITE.url}/aml-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/kyc-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/cookie-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/accessibility`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/complaints`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/disputes`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/bonus-terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/fair-play`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/withdrawal-policy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/betting-rules`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/odds-converter`, lastModified: now, changeFrequency: "yearly", priority: 0.4 },
    { url: `${SITE.url}/agents`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/vip-host`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/maintenance`, lastModified: now, changeFrequency: "yearly", priority: 0.1 },
    { url: `${SITE.url}/release-notes`, lastModified: now, changeFrequency: "monthly", priority: 0.2 },
    { url: `${SITE.url}/data-request`, lastModified: now, changeFrequency: "yearly", priority: 0.2 },
    { url: `${SITE.url}/account-closure`, lastModified: now, changeFrequency: "yearly", priority: 0.2 },
    { url: `${SITE.url}/self-assessment`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/red-envelope`, lastModified: now, changeFrequency: "daily", priority: 0.5 },
    { url: `${SITE.url}/daily-check-in`, lastModified: now, changeFrequency: "daily", priority: 0.5 },
    { url: `${SITE.url}/winners`, lastModified: now, changeFrequency: "daily", priority: 0.4 },
    { url: `${SITE.url}/live-chat`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/app-download`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/download`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/affiliate`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/ambassador`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/help`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/offline`, lastModified: now, changeFrequency: "yearly", priority: 0.1 },
    { url: `${SITE.url}/unauthorized`, lastModified: now, changeFrequency: "yearly", priority: 0.1 },
    { url: `${SITE.url}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/faq`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/support`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE.url}/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/privacy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/responsible-gaming`, lastModified: now, changeFrequency: "yearly", priority: 0.4 },
    { url: `${SITE.url}/login`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/register`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE.url}/bd/en`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/bd/bn`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${SITE.url}/deposit`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/withdraw`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE.url}/dashboard/verification`, lastModified: now, changeFrequency: "monthly", priority: 0.2 },
    { url: `${SITE.url}/dashboard/limits`, lastModified: now, changeFrequency: "monthly", priority: 0.2 },
    { url: `${SITE.url}/dashboard/analytics`, lastModified: now, changeFrequency: "weekly", priority: 0.2 },
    { url: `${SITE.url}/dashboard/tickets`, lastModified: now, changeFrequency: "weekly", priority: 0.2 },
  ];

  const gamePages: MetadataRoute.Sitemap = ALL_GAMES.map((game) => ({
    url: `${SITE.url}/games/${game.id}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: 0.6,
  }));

  const promoPages: MetadataRoute.Sitemap = PROMOTIONS.map((promo) => ({
    url: `${SITE.url}/promotions/${promo.id}`,
    lastModified: now,
    changeFrequency: "monthly",
    priority: 0.6,
  }));

  return [...staticPages, ...gamePages, ...promoPages];
}
